import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Rick and Morty Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ display: "flex", justifyContent: "center", height: "100vh", alignItems: "center"}}>
        <h1>{`MORTY, I've became a NextJS Page, NextJS RIIIIIIIIIIIICK`}</h1>
      </main>
    </div>
  )
}

export default Home
